-- =============================================
-- SEED DATA FOR MINJAL SALON
-- =============================================

-- =============================================
-- INSERT DEFAULT ADMIN USER
-- Password: Admin@123 (hashed with bcrypt)
-- =============================================
INSERT INTO admins (email, password, name, role) VALUES
('admin@minjalsalon.com', '$2a$10$YourHashedPasswordWillGoHere', 'Admin User', 'admin');
-- Note: The password hash will be generated by the backend on first run

-- =============================================
-- INSERT SERVICE CATEGORIES
-- =============================================
INSERT INTO service_categories (name, description, display_order) VALUES
('Hair', 'Professional hair care and styling services', 1),
('Facial', 'Rejuvenating facial treatments', 2),
('Spa', 'Relaxing spa and massage therapies', 3),
('Grooming', 'Complete grooming services', 4);

-- =============================================
-- INSERT SERVICES
-- =============================================
INSERT INTO services (category_id, name, description, price, duration, is_featured) VALUES
-- Hair Services
(1, 'Hair Cut & Styling', 'Professional haircut with expert styling', 999.00, 45, true),
(1, 'Hair Smoothening', 'Smooth and silky hair treatment', 2499.00, 90, true),
(1, 'Hair Coloring', 'Premium hair coloring service', 1999.00, 75, false),
(1, 'Hair Spa', 'Deep conditioning hair spa treatment', 1299.00, 60, false),

-- Facial Services
(2, 'Fruit Facial', 'Natural fruit-based facial treatment', 899.00, 40, true),
(2, 'Gold Facial', 'Luxurious gold facial for radiant skin', 1499.00, 60, true),
(2, 'Anti-Aging Facial', 'Advanced anti-aging treatment', 1999.00, 75, false),
(2, 'Diamond Facial', 'Premium diamond facial treatment', 2499.00, 90, false),

-- Spa Services
(3, 'Head Massage', 'Relaxing head and scalp massage', 699.00, 30, false),
(3, 'Body Spa Therapy', 'Full body spa and relaxation', 1999.00, 90, true),
(3, 'Aroma Therapy', 'Therapeutic aroma massage', 1599.00, 60, false),

-- Grooming Services
(4, 'Beard Styling', 'Professional beard trimming and styling', 399.00, 20, false),
(4, 'Clean Shave', 'Classic clean shave service', 299.00, 15, false),
(4, 'Complete Grooming', 'Full grooming package', 899.00, 45, true);

-- =============================================
-- INSERT CATALOGUE ITEMS
-- =============================================
INSERT INTO catalogue_items (service_id, title, description, price, duration, is_visible, display_order) VALUES
(1, 'Premium Hair Cut & Styling', 'Expert haircut with personalized styling consultation. Includes wash, cut, and blow dry.', 999.00, 45, true, 1),
(2, 'Hair Smoothening Treatment', 'Get silky smooth hair with our premium smoothening treatment. Long-lasting results.', 2499.00, 90, true, 2),
(5, 'Refreshing Fruit Facial', 'Natural fruit extracts for glowing skin. Perfect for all skin types.', 899.00, 40, true, 3),
(6, 'Luxurious Gold Facial', 'Experience the luxury of gold-infused facial treatment for radiant skin.', 1499.00, 60, true, 4),
(10, 'Relaxing Body Spa', 'Complete body spa therapy for ultimate relaxation and rejuvenation.', 1999.00, 90, true, 5),
(14, 'Complete Grooming Package', 'All-in-one grooming solution including haircut, beard styling, and facial.', 899.00, 45, true, 6);

-- =============================================
-- INSERT OFFERS
-- =============================================
INSERT INTO offers (title, description, is_active) VALUES
('Grand Opening Offer - 20% OFF on all services!', 'Limited time offer for new customers. Book your appointment now.', true);

-- =============================================
-- INSERT CONTENT PAGES
-- =============================================
INSERT INTO content_pages (page_key, title, content) VALUES
('about', 'About Minjal Salon', 'Welcome to Minjal Salon, Bhubaneswar''s premier destination for luxury beauty and grooming services. We combine expert craftsmanship with premium products to deliver exceptional results.'),
('brand_story', 'Our Story', 'Founded with a passion for beauty and excellence, Minjal Salon has been serving the community with dedication and expertise. Our journey began with a simple vision: to create a space where elegance meets expert care.'),
('philosophy', 'Our Philosophy', 'We believe in personalized care, using only the finest products and techniques. Every client is unique, and we tailor our services to meet individual needs and preferences.'),
('owner', 'Meet Our Founder', 'Our founder brings years of experience in the beauty industry, with a commitment to excellence and customer satisfaction. The vision is to make every visit a memorable experience.');

-- =============================================
-- INSERT SAMPLE ENQUIRIES
-- =============================================
INSERT INTO enquiries (name, phone, email, message) VALUES
('Rahul Sharma', '9876543210', 'rahul@example.com', 'I would like to know about bridal makeup packages.'),
('Priya Patel', '9123456789', 'priya@example.com', 'Do you offer home service for hair treatments?');

-- =============================================
-- SUCCESS MESSAGE
-- =============================================
SELECT 'Seed data inserted successfully!' AS message;
